name: Export AAR

on:
  push:
    branches:
      - develop

jobs:
  publish:
    name: Build and export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: '11'

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew clean :mozo-sdk:assembleRelease

        # Generates other artifacts (javadocJar is optional)
      - name: Source jar and dokka
        run: ./gradlew androidSourcesJar javadocJar

        # Upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: mozo-sdk-artifact
          path: ./mozo-sdk/build/outputs