name: Remove old artifacts

on:
  push:
    branches:
    - master
    - release/*
    - hotfix/*

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: '2 weeks'
          skip-tags: true